//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int courseID { get; set; }
        public string courseName { get; set; }
        public int credits { get; set; }
        public string courseDescribtion { get; set; }
        public Nullable<int> price { get; set; }
        public bool IsCourseActive { get; set; }
        public Nullable<CourseLevel> level { get; set; }
        public Nullable<RatingCourse> Rating { get; set; }
        public Nullable<int> Level2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual CourseLevel1 CourseLevel { get; set; }
    }
}
